; MAPF/DU domain (FOND version) with 16 worlds for 4 agents
; Author: Thorsten Engesser
(define (domain mapfdu_4_agents)
  (:types agt world pos)
  (:constants w0 w1 w2 w3 w4 w5 w6 w7 w8 w9 w10 w11 w12 w13 w14 w15 - world)
  (:predicates
    (at ?a - agt ?p - pos)
    (adj ?p1 ?p2 - pos)
    (stopped ?a - agt)
    (goal ?w - world ?a - agt ?p - pos)
    (ind ?a - agt ?w1 ?w2 - world)
    (des ?w - world)
    (next-choose)
    (next-move ?a - agt ?p1 ?p2 - pos)
    (next-annc ?a - agt ?p - pos))
  (:action choose-move ; UNFAIR ACTION!
     :parameters (?a - agt ?w - world ?p1 ?p2 - pos)
     :precondition (and (des ?w) (next-choose)
                        (at ?a ?p1) (adj ?p1 ?p2)
                        (not (exists (?a2 - agt) (at ?a2 ?p2)))
                        (not (stopped ?a)))
     :effect (and (next-move ?a ?p1 ?p2) (not (next-choose))
                  (oneof 
                         (when (and (ind ?a ?w w0) (not (= ?w w0)))
                               (and (not (des ?w)) (des w0)))
                         (when (and (ind ?a ?w w1) (not (= ?w w1)))
                               (and (not (des ?w)) (des w1)))
                         (when (and (ind ?a ?w w2) (not (= ?w w2)))
                               (and (not (des ?w)) (des w2)))
                         (when (and (ind ?a ?w w3) (not (= ?w w3)))
                               (and (not (des ?w)) (des w3)))
                         (when (and (ind ?a ?w w4) (not (= ?w w4)))
                               (and (not (des ?w)) (des w4)))
                         (when (and (ind ?a ?w w5) (not (= ?w w5)))
                               (and (not (des ?w)) (des w5)))
                         (when (and (ind ?a ?w w6) (not (= ?w w6)))
                               (and (not (des ?w)) (des w6)))
                         (when (and (ind ?a ?w w7) (not (= ?w w7)))
                               (and (not (des ?w)) (des w7)))
                         (when (and (ind ?a ?w w8) (not (= ?w w8)))
                               (and (not (des ?w)) (des w8)))
                         (when (and (ind ?a ?w w9) (not (= ?w w9)))
                               (and (not (des ?w)) (des w9)))
                         (when (and (ind ?a ?w w10) (not (= ?w w10)))
                               (and (not (des ?w)) (des w10)))
                         (when (and (ind ?a ?w w11) (not (= ?w w11)))
                               (and (not (des ?w)) (des w11)))
                         (when (and (ind ?a ?w w12) (not (= ?w w12)))
                               (and (not (des ?w)) (des w12)))
                         (when (and (ind ?a ?w w13) (not (= ?w w13)))
                               (and (not (des ?w)) (des w13)))
                         (when (and (ind ?a ?w w14) (not (= ?w w14)))
                               (and (not (des ?w)) (des w14)))
                         (when (and (ind ?a ?w w15) (not (= ?w w15)))
                               (and (not (des ?w)) (des w15))))))
  (:action choose-announce ; UNFAIR ACTION!
     :parameters (?a - agt ?w - world ?p - pos)
     :precondition (and (des ?w) (next-choose)
                        (at ?a ?p) (goal ?w ?a ?p)
                        (not (stopped ?a)))
     :effect (and (next-annc ?a ?p) (not (next-choose))
                  (oneof 
                         (when (and (ind ?a ?w w0) (not (= ?w w0)))
                               (and (not (des ?w)) (des w0)))
                         (when (and (ind ?a ?w w1) (not (= ?w w1)))
                               (and (not (des ?w)) (des w1)))
                         (when (and (ind ?a ?w w2) (not (= ?w w2)))
                               (and (not (des ?w)) (des w2)))
                         (when (and (ind ?a ?w w3) (not (= ?w w3)))
                               (and (not (des ?w)) (des w3)))
                         (when (and (ind ?a ?w w4) (not (= ?w w4)))
                               (and (not (des ?w)) (des w4)))
                         (when (and (ind ?a ?w w5) (not (= ?w w5)))
                               (and (not (des ?w)) (des w5)))
                         (when (and (ind ?a ?w w6) (not (= ?w w6)))
                               (and (not (des ?w)) (des w6)))
                         (when (and (ind ?a ?w w7) (not (= ?w w7)))
                               (and (not (des ?w)) (des w7)))
                         (when (and (ind ?a ?w w8) (not (= ?w w8)))
                               (and (not (des ?w)) (des w8)))
                         (when (and (ind ?a ?w w9) (not (= ?w w9)))
                               (and (not (des ?w)) (des w9)))
                         (when (and (ind ?a ?w w10) (not (= ?w w10)))
                               (and (not (des ?w)) (des w10)))
                         (when (and (ind ?a ?w w11) (not (= ?w w11)))
                               (and (not (des ?w)) (des w11)))
                         (when (and (ind ?a ?w w12) (not (= ?w w12)))
                               (and (not (des ?w)) (des w12)))
                         (when (and (ind ?a ?w w13) (not (= ?w w13)))
                               (and (not (des ?w)) (des w13)))
                         (when (and (ind ?a ?w w14) (not (= ?w w14)))
                               (and (not (des ?w)) (des w14)))
                         (when (and (ind ?a ?w w15) (not (= ?w w15)))
                               (and (not (des ?w)) (des w15))))))
  (:action move
     :parameters (?a - agt ?w - world ?p1 ?p2 - pos)
     :precondition (and (des ?w) (next-move ?a ?p1 ?p2))
     :effect (and (not (at ?a ?p1)) (at ?a ?p2)
                  (not (next-move ?a ?p1 ?p2))
                  (next-choose)))
  (:action announce
     :parameters (?a - agt ?w - world ?p - pos)
     :precondition (and (des ?w) (next-annc ?a ?p)
                        (goal ?w ?a ?p))
     :effect (and (stopped ?a)
                  (not (next-annc ?a ?p)) (next-choose)
                  (forall (?w1 ?w2 - world ?a1 - agt)
                          (when (not (goal ?w1 ?a ?p))
                                (and (not (ind ?a1 ?w1 ?w2))
                                     (not (ind ?a1 ?w2 ?w1))))))))
